version: '3.4'
services:
  traefik:
    image: traefik:v2.2
    container_name: traefik
    command:
      - --log.level=DEBUG
      - --log.filePath=/logs/traefik.log
      - --api.dashboard=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./traefik_dynamic.toml:/traefik_dynamic.toml
      - ./acme.json:/acme.json
      - ./logs/:/logs/
    networks:
      - web

networks:
  web:
    external: true