[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"
[api]
  dashboard = true
[certificatesResolvers.lets-encrypt.acme]
  # Change the email address and remove the line below to accept the Let's Encrypt
  email = "EMAIL@HOST"
  storage = "acme.json"
  [certificatesResolvers.lets-encrypt.acme.tlsChallenge]
[providers.docker]
  watch = true
  network = "web"
[providers.file]
  filename = "traefik_dynamic.toml"